In [1]:
import numpy

In [5]:
# 32-bit float value has a data size of 4 bytes
WORD_LENGTH = 4

# the number of x-y grids.
NUM_X = 5
NUM_Y = 5

# array size in 1 dimension
RECORD_LENGTH = NUM_X * NUM_Y

record = numpy.fromfile(
    file='../database/precipitation.bin',
    dtype=numpy.float32,
    offset=0*WORD_LENGTH,
    count=RECORD_LENGTH,
)

record_2d = record.reshape([NUM_Y, NUM_X])

print(record_2d)

[[12.   8.5  2.1  0.   4.9]
 [10.2  7.9  6.2  0.7  0. ]
 [ 9.8  8.5  5.4  1.1  2.8]
 [ 8.9  4.5  2.1  0.   0. ]
 [ 6.   8.5  0.8  0.5  0. ]]


---
### Define NDArray (Numpy Data Array)

Equivalent Fortran^90 code:
```f90
real :: matrix(3, 3)
matrix = reshape([ &
    1, 4, 7, &
    2, 5, 8, &
    3, 6, 9  &
], [3, 3])
```

In [3]:
matrix = numpy.array(
    object=[
        1, 2, 3,
        4, 5, 6,
        7, 8, 9,
    ],
    dtype=numpy.float32,
).reshape([3, 3])

print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


---
Pythonにはもともと組み込みの配列が存在する。

NumPyの配列は組み込みの配列とは別物なので注意。

似ている機能も多いが。

In [4]:
matrix_built_in = [
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
]

# Get the value in the 1st row, 2nd column
# -> both will return `2`
matrix_built_in[0][1]
matrix[0][1]

# Get the length of the array
# -> both will return `3`
len(matrix_built_in)
len(matrix)

# Get the 2nd row by `pop` method
matrix_built_in.pop(1)
"""
matrix.pop()
    this will raise error because NDArray objects
    has no attribute 'pop'.
"""

None

---
### Matrix Calculation
NDArrayは多くの行列計算をサポートする. その構文はFortran ^90と共通する部分が多い

##### Arithmetic
`+`, `-`, `*`, `/`, and other basic arithmetical operations.

```
! Equivalent Fortran^90 code:
result_arithmetic(:, :) = (matrix(:, :) * 2) + 10
```


In [9]:
result_arithmetic = (matrix[:, :] * 2) + 1

print(result_arithmetic)

[[ 3.  5.  7.]
 [ 9. 11. 13.]
 [15. 17. 19.]]


##### `where` method

条件に従って値を書き換える

```f90
! Equivalent Fortran^90 code:
where (matrix(:, :) > 4.999e+0)
    mask = 1.0e+0
else where
    mask = 0.0e+0
end where
```


In [10]:
mask = numpy.where(
    matrix > 4.999e+0,
    1.0e+0,
    0.0e+0,
)

print(mask)

[[0. 0. 0.]
 [0. 1. 1.]
 [1. 1. 1.]]


In [1]:
print('yes')

yes
