In [1]:
import numpy

---

The numpy library treats arrays as NDArray object.

You can create an NDArray object, for example using the `numpy.array` method.

In [2]:
ndarray_2d = numpy.array([[1.0, 2.0], [3.0, 4.0]])

print(ndarray_2d)

[[1. 2.]
 [3. 4.]]


You can access each element in the same way as a `list` type.

In [3]:
ndarray_2d[1][0]

3.0

NDArray is an array-like class specialized for numerical calculation.

for example, `+`, `-`, `*`, `/`, and other basic arithmetical operations will be broadcasted to the entire array.

This behavior is same as Fortran ^90.


In [4]:
result_arithmetic = (ndarray_2d * 2) + 1
print(result_arithmetic)

[[3. 5.]
 [7. 9.]]


Note that `list` (python built-in array class) and `ndarray` are not the same.

In [5]:
list_2d = [[1.0, 2.0], [3.0, 4.0]]

# this will be an unexpected result.
result_list = list_2d * 2

print(result_list)

[[1.0, 2.0], [3.0, 4.0], [1.0, 2.0], [3.0, 4.0]]


---

Read binary file such as distributed precipitation data.

First, define control parameters for the binary file to read.
These values are usually provided with binary files as a `.ctl` file.

In [6]:
NUM_X = 5
NUM_Y = 5
NUM_MESH = NUM_X * NUM_Y
WORD_LENGTH = 4
RECORD_LENGTH = NUM_MESH * WORD_LENGTH

Then, read file as 1-dimensional NDArray (NumPy Data Array).

In [7]:
file_path = '../database/precipitation.bin'

record = numpy.fromfile(
    file=file_path,
    dtype=numpy.float32,
    offset=0*RECORD_LENGTH,
    count=NUM_MESH,
)

print(record)

[12.   8.5  2.1  0.   4.9 10.2  7.9  6.2  0.7  0.   9.8  8.5  5.4  1.1
  2.8  8.9  4.5  2.1  0.   0.   6.   8.5  0.8  0.5  0. ]


Reshape the array.

In [8]:
record_2d = numpy.reshape(record, [NUM_Y, NUM_X])

print(record_2d)

[[12.   8.5  2.1  0.   4.9]
 [10.2  7.9  6.2  0.7  0. ]
 [ 9.8  8.5  5.4  1.1  2.8]
 [ 8.9  4.5  2.1  0.   0. ]
 [ 6.   8.5  0.8  0.5  0. ]]


the direction of th y-axis is different depending on the file. Some files are South-to-North, others vice versa.

Invert the y-axis with a `flipud` function.

In [9]:
record_ud = numpy.flipud(record_2d)

print(record_ud)

[[ 6.   8.5  0.8  0.5  0. ]
 [ 8.9  4.5  2.1  0.   0. ]
 [ 9.8  8.5  5.4  1.1  2.8]
 [10.2  7.9  6.2  0.7  0. ]
 [12.   8.5  2.1  0.   4.9]]


### References
- [ndarray - NumPy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
- [broadcasting - NumPy](https://numpy.org/doc/stable/user/basics.broadcasting.html)
- [fromfile - NumPy](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html)
- [reshape - NumPy](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)
- [scalars - NumPy](https://numpy.org/doc/stable/reference/arrays.scalars.html)