### practice #4.1
Try the following process:
- import NumPy package.
- read the first record in the `../dastabase/precipitation-24h.bin` file.
- reshape to 2-dimensional array.

`flipud` is not needed.

The control file is given below.

In [47]:
NUM_X = 5
NUM_Y = 5
NUM_MESH = NUM_X * NUM_Y
WORD_LENGTH = 4
RECORD_LENGTH = NUM_MESH * WORD_LENGTH

Result:
```
[[12.612703    8.753024    2.3407445   1.4685531   5.28154   ]
 [11.120362    8.354229    5.2669816   1.5054457   0.92759746]
 [11.29438     7.1976237   4.816882    0.4887265   2.3902524 ]
 [ 8.0598955   3.0899985   3.301363    0.6795741   0.        ]
 [ 7.4743543   9.468013    0.21009248  0.          0.26698786]]
```


Example code:
```
import numpy

file_path = '../database/precipitation_24h.bin'
record = numpy.fromfile(
    file=file_path,
    dtype=numpy.float32,
    offset=0*RECORD_LENGTH,
    count=NUM_MESH,
)

record_2d = numpy.reshape(record, [NUM_Y, NUM_X])

print(record_2d)
```

---
### practice #4.2
Multiply the mesh area to derive the volume of rainfall [unit: ton (m^3)].

- Each mesh size in the x direction is 11km (0.1 degree).
- Each mesh size in the y direction is 11km (0.1 degree).
- The unit of precipitation is millimeter.


Result:
```
[[1526137.2   1059116.     283230.12   177694.92   639066.4  ]
 [1345564.    1010861.7    637304.8    182158.94   112239.3  ]
 [1366620.1    870912.5    582842.75    59135.91   289220.53 ]
 [ 975247.4    373889.84   399464.94    82228.47        0.   ]
 [ 904396.9   1145629.6     25421.191       0.      32305.531]]
```

Example code:
```
MESH_AREA_IN_METER = 11.0e+3 * 11.0e+3
record_2d_in_meter = record_2d * 1.0e-3

record_q = record_2d_in_meter * MESH_AREA_IN_METER

print(record_q)
```

---

### practice #4.3

Get 24h time series data for the **2nd** from the **left** and the **4th** from the **top** as shown in the figure below:

```
- - - - -
- - - - -
- - - - -
- x - - -
- - - - -
```

Result:
```
[3.0899985, 1.6968727, 1.4542011, 1.1133314, 1.58915, 2.6248264, 2.5769398, 3.1597853, 1.94741, 1.4672701, 1.2250593, 2.181072, 1.217413, 2.0016506, 1.9193329, 2.1685753, 3.5202487, 4.329589, 5.7965198, 5.8334913, 6.129581, 7.07681, 7.6121306, 8.938053]
```

Example Code:
```
file_path = '../database/precipitation_24h.bin'

x_index = 2 - 1
y_index = 4 - 1

time_series = []

for i_hour in range(24):
    record = numpy.fromfile(
        file=file_path,
        dtype=numpy.float32,
        offset=i_hour*RECORD_LENGTH,
        count=NUM_MESH,
    )
    record_2d = numpy.reshape(record, [NUM_Y, NUM_X])
    value = record_2d[y_index][x_index]
    time_series = [*time_series, value]

print(time_series)
```

Or shorter code:
```
file_path = '../database/precipitation_24h.bin'

x_index = 2 - 1
y_index = 4 - 1

time_series = [
    numpy.fromfile(
        file=file_path,
        dtype=numpy.float32,
        offset=i_hour*RECORD_LENGTH,
        count=NUM_MESH,
    )[x_index + y_index * NUM_X]
    for i_hour in range(24)
]

print(time_series)
```